name: ultra_deriv_ai
description: AI trading analysis system
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0

flutter:
  uses-material-design: true